# Sort Serach and Counting Function

In [12]:
import numpy as np

In [13]:
arr=np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [14]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [15]:
np.sort(arr) 

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [16]:
np.searchsorted(arr,34)

12

In [17]:
arr1=np.array([0,345,454,0,0,0,0,0])

In [20]:
# Checking the non zero data 
np.count_nonzero(arr1)

2

In [19]:
np.where(arr>6)
# Will return the indexes of the data that is greater than 6 

(array([5, 8]),)

In [22]:
np.where(arr>=4) # indexes of data having greater than and equal to value 4

(array([ 0,  2,  3,  4,  5,  8,  9, 10, 11]),)

In [25]:
np.extract(arr>6,arr)
# Will extract the data that is greater than 6

array([ 72, 455])

### Byte Swapping

In [42]:
arr.byteswap() # Will show the byte representation of the data present in the array

array([-8214002770370363392,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

### Copies and Views

In [43]:
arr

array([654,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [44]:
a=np.copy(arr) # Will create a copy of the data in the different location from the earlier
# This is known as creating the Deep copy

In [36]:
b=arr.view()

In [37]:
b

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [38]:
b[0]=654

In [39]:
b

array([654,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [40]:
arr

array([654,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [41]:
# Changes made in the view will affect the both, The view copy and teh original copy as well
# View does not create a new copy instead it refers the data to the original location 

### Numpy- Matrix Library

In [45]:
import numpy.matlib as nm

In [49]:
nm.zeros((5,5)) # Will generate the matrix having all values as zero 

matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [51]:
nm.ones((2,2)) # Will generate the 2*2 matrix having all values as 1

matrix([[1., 1.],
        [1., 1.]])

In [53]:
nm.eye(5) # Identity matrix of 5*5

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

### Numpy-Linear Algebra

In [58]:
arr1=np.random.randint([[2,3],[4,5]])

In [59]:
arr2=np.random.randint([[5,3],[2,5]])

In [60]:
np.dot(arr1,arr2)

array([[0, 1],
       [0, 2]])

In [62]:
arr1@arr2 # Both are same 

array([[0, 1],
       [0, 2]])