# Array Manipulation

In [4]:
import numpy as np

In [5]:
arr=np.random.randint(1,10,(3,4))

In [6]:
arr

array([[1, 4, 2, 7],
       [6, 9, 7, 2],
       [3, 6, 8, 8]])

In [7]:
arr.reshape(6,2)

array([[1, 4],
       [2, 7],
       [6, 9],
       [7, 2],
       [3, 6],
       [8, 8]])

In [8]:
arr.reshape(7,2)
# Will raise error as its not possible to arrange 12 elements in the required way 

ValueError: cannot reshape array of size 12 into shape (7,2)

In [9]:
arr.T

array([[1, 6, 3],
       [4, 9, 6],
       [2, 7, 8],
       [7, 2, 8]])

In [10]:
arr.flatten()
# Converts any data into 1-D

array([1, 4, 2, 7, 6, 9, 7, 2, 3, 6, 8, 8])

In [11]:
arr1=np.array([1,2,3,3,4])

In [12]:
arr1.ndim

1

In [13]:
np.expand_dims(arr1,axis=1) # will expend along the column

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [14]:
np.expand_dims(arr1,axis=0) # will expand along the Row

array([[1, 2, 3, 3, 4]])

In [15]:
arr

array([[1, 4, 2, 7],
       [6, 9, 7, 2],
       [3, 6, 8, 8]])

In [16]:
np.squeeze(arr)

array([[1, 4, 2, 7],
       [6, 9, 7, 2],
       [3, 6, 8, 8]])

In [17]:
data=np.array([[1],[2],[3]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.squeeze(data) # will squeze only in case when single element is avilable 

array([1, 2, 3])

In [20]:
np.repeat(arr1,3) #repeated 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [21]:
roll_array=np.roll(arr1,shift=2) # roll the data by 2 shifts like 1 present at very starting will move 2 place and reaching on place of 3

In [22]:
roll_array

array([3, 4, 1, 2, 3])

In [23]:
arr1

array([1, 2, 3, 3, 4])

In [24]:
np.diag(arr1) # Will put the entire data in the diagonal 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [25]:
# Binary Opertaion in NUMPY

In [28]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [29]:
arr1

array([[3, 7, 2, 3],
       [3, 1, 7, 6],
       [2, 5, 9, 5]])

In [30]:
arr2

array([[3, 1, 8, 6],
       [1, 4, 7, 5],
       [3, 9, 3, 7]])

In [31]:
# Binary operation in Arr1 and Arr2

In [32]:
arr1+arr2

array([[ 6,  8, 10,  9],
       [ 4,  5, 14, 11],
       [ 5, 14, 12, 12]])

In [33]:
arr1*arr2

array([[ 9,  7, 16, 18],
       [ 3,  4, 49, 30],
       [ 6, 45, 27, 35]])

In [34]:
arr1/arr2

array([[1.        , 7.        , 0.25      , 0.5       ],
       [3.        , 0.25      , 1.        , 1.2       ],
       [0.66666667, 0.55555556, 3.        , 0.71428571]])

In [35]:
arr1-arr2

array([[ 0,  6, -6, -3],
       [ 2, -3,  0,  1],
       [-1, -4,  6, -2]])

In [36]:
# All the functions will be performed by the indexwise operation 

In [38]:
# Reminder Operation 
arr1%arr2

array([[0, 0, 2, 3],
       [0, 1, 0, 1],
       [2, 5, 0, 5]])

In [39]:
arr1**arr2

array([[     27,       7,     256,     729],
       [      3,       1,  823543,    7776],
       [      8, 1953125,     729,   78125]])

In [42]:
arr1 & arr2 # Performing and operation 

array([[3, 1, 0, 2],
       [1, 0, 7, 4],
       [2, 1, 1, 5]])

In [43]:
~arr1 # Negate Operation 

array([[ -4,  -8,  -3,  -4],
       [ -4,  -2,  -8,  -7],
       [ -3,  -6, -10,  -6]])

In [44]:
arr1|arr2 # or Operation 

array([[ 3,  7, 10,  7],
       [ 3,  5,  7,  7],
       [ 3, 13, 11,  7]])

# Numpy-String Function

In [49]:
arr=np.array(['lucky','yash']) # dtype is U5 ie String

In [50]:
# Converting the array into Upper 
np.char.upper(arr)

array(['LUCKY', 'YASH'], dtype='<U5')

In [51]:
# Converting to Title case 
np.char.title(arr)

array(['Lucky', 'Yash'], dtype='<U5')

In [52]:
np.char.capitalize(arr)

array(['Lucky', 'Yash'], dtype='<U5')

In [53]:
# All the functions present in the String are avilable in the Python under Char

# Numpy Mathematical Function 

In [55]:
np.sin(arr1)

array([[ 0.14112001,  0.6569866 ,  0.90929743,  0.14112001],
       [ 0.14112001,  0.84147098,  0.6569866 , -0.2794155 ],
       [ 0.90929743, -0.95892427,  0.41211849, -0.95892427]])

In [56]:
np.cos(arr1)

array([[-0.9899925 ,  0.75390225, -0.41614684, -0.9899925 ],
       [-0.9899925 ,  0.54030231,  0.75390225,  0.96017029],
       [-0.41614684,  0.28366219, -0.91113026,  0.28366219]])

In [57]:
np.tan(arr1)

array([[-0.14254654,  0.87144798, -2.18503986, -0.14254654],
       [-0.14254654,  1.55740772,  0.87144798, -0.29100619],
       [-2.18503986, -3.38051501, -0.45231566, -3.38051501]])

In [58]:
np.tanh(arr1)

array([[0.99505475, 0.99999834, 0.96402758, 0.99505475],
       [0.99505475, 0.76159416, 0.99999834, 0.99998771],
       [0.96402758, 0.9999092 , 0.99999997, 0.9999092 ]])

In [59]:
np.log10(arr1)

array([[0.47712125, 0.84509804, 0.30103   , 0.47712125],
       [0.47712125, 0.        , 0.84509804, 0.77815125],
       [0.30103   , 0.69897   , 0.95424251, 0.69897   ]])

In [60]:
np.exp(arr1)

array([[2.00855369e+01, 1.09663316e+03, 7.38905610e+00, 2.00855369e+01],
       [2.00855369e+01, 2.71828183e+00, 1.09663316e+03, 4.03428793e+02],
       [7.38905610e+00, 1.48413159e+02, 8.10308393e+03, 1.48413159e+02]])

In [61]:
np.sqrt(arr1)

array([[1.73205081, 2.64575131, 1.41421356, 1.73205081],
       [1.73205081, 1.        , 2.64575131, 2.44948974],
       [1.41421356, 2.23606798, 3.        , 2.23606798]])

In [62]:
np.power(arr1,2)

array([[ 9, 49,  4,  9],
       [ 9,  1, 49, 36],
       [ 4, 25, 81, 25]])

In [63]:
np.power(arr1,3)

array([[ 27, 343,   8,  27],
       [ 27,   1, 343, 216],
       [  8, 125, 729, 125]])

In [64]:
np.mean(arr1)

4.416666666666667

In [65]:
np.median(arr1)

4.0

In [66]:
np.std(arr1)

2.3614378858841256

In [67]:
np.var(arr1)

5.576388888888888

In [68]:
np.min(arr1)

1

In [69]:
np.max(arr1)

9