Numpy

In [1]:
import numpy as np
#Numpy is all about dealing with the arrays 

In [2]:
l=[1,2,3,4]

In [5]:
ar=np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [9]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
np.asarray(l)

array([1, 2, 3, 4])

In [11]:
type(np.asarray(l))

numpy.ndarray

In [12]:
np.asanyarray(np.asarray(l))

array([1, 2, 3, 4])

In [13]:
# All the 3 array, asarray and asanyarray is used to convert into the Pure array

In [18]:
b=np.matrix([1,2,3,4])
# Matrix is 2D by default

In [19]:
b

matrix([[1, 2, 3, 4]])

In [20]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [21]:
# Matrix wont be converted into the Array because Matrix is subset of Array

In [22]:
a=np.array(l)

In [23]:
a

array([1, 2, 3, 4])

In [24]:
c=a

In [25]:
c

array([1, 2, 3, 4])

In [26]:
a

array([1, 2, 3, 4])

In [27]:
c[0]

1

In [28]:
c[0] = 100

In [29]:
c

array([100,   2,   3,   4])

In [30]:
a

array([100,   2,   3,   4])

In [32]:
# The changes made in the one variable will be affected in the second one too as we can see that the changes made in the c will be affecting a as well

In [33]:
# This is known as swallow copy as hanges made in the one are easily reflaected in the other one 

In [35]:
d=np.copy (a)

In [36]:
d

array([100,   2,   3,   4])

In [37]:
a

array([100,   2,   3,   4])

In [41]:
a[1]=400

In [42]:
a

array([100, 400, 400,   4])

In [40]:
d

array([100,   2,   3,   4])

In [43]:
# Here the changes made in the a are only being shown in the a only as d is created using the copy 
# This is known as Deep Copy 

In [44]:
np.fromfunction(lambda i,j:i==j,(3,3) ) # Fromfunction is used to generate the data as per the function present inside 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
# Will be forming 3*3 Matrix and will check i=j or not if yes then True else False

In [48]:
np.fromfunction(lambda i,j:i*j,(3,3)) # Will multiply (0,1,2) and (0,1,2)

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [54]:
iterable=(i*i for i in range(5))

In [55]:
np.fromiter(iterable,float)
# fromiter can also be used for making arrays

array([ 0.,  1.,  4.,  9., 16.])

In [57]:
np.fromstring('234 234',sep=' ') # converts the string into the array sep is used for telling the seperator as here is ' '

array([234., 234.])

In [62]:
np.fromstring('2,3,4',sep=',')

array([2., 3., 4.])

In [63]:
# Data Types in Numpy

In [64]:
l=[1,2,3,4,5,6]

In [66]:
ar=np.array(l)

In [67]:
ar

array([1, 2, 3, 4, 5, 6])

In [71]:
ar.ndim # This is used to find the size of the array

1

In [72]:
ar2=np.array([[1,2,3,4],[2,3,4,5]]) # This is 2D array

In [73]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [75]:
ar2.ndim

2

In [76]:
ar2.size # Will tell the number of elements present in the array

8

In [77]:
ar.size

6

In [80]:
ar.shape # Will be telling the shape of teh array

(6,)

In [81]:
ar2.shape

(2, 4)

In [82]:
ar.dtype

dtype('int64')

In [84]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [85]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [88]:
ar22.dtype

dtype('float64')

In [87]:
# Here only one was float(1.4) and due to that it changed for all

In [90]:
list(range(5))

[0, 1, 2, 3, 4]

In [92]:
list(range(0.1,5.1)) # Float objects can not be accepted in the range function 
# Error will be raised up due to that 

TypeError: 'float' object cannot be interpreted as an integer

In [94]:
# You can give float as start or end by using numpy

In [98]:
np.arange(2.3,5.6) # The jump will be 1 by default

array([2.3, 3.3, 4.3, 5.3])

In [99]:
np.arange(2.3,5.6,0.3) # Here jump is 0.3

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [100]:
list(np.arange(2.3,5.6,0.3) ) #converting it into the list

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [105]:
np.linspace(1,5,10) #will divide the interval in 10 equal spaces

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [107]:
np.zeros(5) # Will produce 5 zeros

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((3,4)) # all zero in the provided dimension 
# In 2D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
np.zeros((3,4,5)) # all zero in the provided dimension
# In 3D 

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [115]:
ar4=np.zeros((2,3,4,5)) # all zero in the provided dimension

In [116]:
ar4

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [117]:
ar4.ndim

4

In [118]:
np.ones(2)

array([1., 1.])

In [122]:
np.ones((2,2))
# Can do all the operations as we have done in the zeros

array([[1., 1.],
       [1., 1.]])

In [124]:
on=np.ones((2,3,5))

In [125]:
on

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [128]:
on+7 # Will add 7 in all the elements 

array([[[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]],

       [[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]]])

In [129]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
np.eye(4) # identity matrix of the given 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [132]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [133]:
np.logspace(2,5,10) # By default the base will be 10 

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [135]:
np.logspace(2,5,10,base=2) # Can change the base as well

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [141]:
# Generates the random data between the given dimension
arr=np.random.randn(3,4)

In [144]:
arr

array([[ 0.20621087,  0.73997997, -0.58295597,  0.31616526],
       [ 0.54116592,  0.95357051, -0.10475349,  0.10922092],
       [ 0.65548122, -1.45197988,  1.7533838 , -0.24960497]])

In [142]:
import pandas as pd

In [143]:
# Convert into Data Frame
pd.DataFrame(arr)

0         1         2         3
0  0.206211  0.739980 -0.582956  0.316165
1  0.541166  0.953571 -0.104753  0.109221
2  0.655481 -1.451980  1.753384 -0.249605

In [146]:
arr2=np.random.rand(3,4)

In [148]:
arr2

array([[0.20004251, 0.9418571 , 0.66587199, 0.39966875],
       [0.86528543, 0.43131042, 0.3574646 , 0.07042487],
       [0.59383569, 0.44618   , 0.00504743, 0.01117287]])

In [149]:
# The difference between randn and rand is randn will be producing the data having mean=0 and std deviation=1

In [155]:
arr2=np.random.randint(1,110,(300,400)) # producing 3*4 data between 1 and 110

In [156]:
arr2

array([[ 93,  35,  12, ...,  30,  21,  32],
       [ 37,  43,  92, ...,  15, 102,   4],
       [  4,   4,  42, ...,   2,  97,  62],
       ...,
       [ 79,  36,  28, ...,  68,  11,  26],
       [ 87,  71,  61, ...,  52,  95,  69],
       [ 65,  88,  56, ...,  60,  28,  59]])

In [159]:
# Converting it into the DataFrame
df1=pd.DataFrame(arr2)

In [161]:
df1

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     93   35   12  109   94   87   60    2   42    2  ...   46    7   55   
1     37   43   92   97   23   96    5   78   93   93  ...  105   67   76   
2      4    4   42   47   62   24   39   29   80   42  ...   93   55   27   
3     64   80   77    7  107   61   81   91   25   91  ...  108   77   43   
4     80   54   77   46  103   10   96   77    4   67  ...   94   94   99   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   98    7   31   42   11   77    4  104   12   22  ...  106   48  109   
296   55   57   65   28  108   60   32   70   99   10  ...   87   24   94   
297   79   36   28   90    9   32   29   90   49  102  ...   78   10   98   
298   87   71   61   50   73   71   19  108   78   15  ...   41   62  106   
299   65   88   56    7   89   64    4   26   17   24  ...   68    9   24   

     393  394  395  396  397  398  399  
0     96   38   93   76   30   21   32  
1     72   34   61   65   15  102    4  
2     31   95   99   72    2   97   62  
3     70   93   55   35   74   10   63  
4    101   30   25   81   56   27   52  
..   ...  ...  ...  ...  ...  ...  ...  
295   30   87  100  107   41   39   48  
296  105    1   73  106   42  109    2  
297    8   20  100   12   68   11   26  
298   98   20   77   84   52   95   69  
299    1   19   49    8   60   28   59  

[300 rows x 400 columns]

In [164]:
# Storing the same data into the CSV File
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [165]:
arr=np.random.rand(3,4)

In [166]:
arr

array([[0.21575596, 0.99924398, 0.06858773, 0.19386894],
       [0.45247623, 0.77078668, 0.84472911, 0.07078185],
       [0.47437914, 0.98580774, 0.61239199, 0.57302789]])

In [168]:
arr.reshape(6,2) # Same data will be arranged in the 6*2

array([[0.21575596, 0.99924398],
       [0.06858773, 0.19386894],
       [0.45247623, 0.77078668],
       [0.84472911, 0.07078185],
       [0.47437914, 0.98580774],
       [0.61239199, 0.57302789]])

In [176]:
arr1=arr.reshape(6,-2)
# if one dimension is unclear to yoy so just mention any negative number to get the data as per the requirement

In [178]:
arr1

array([[0.21575596, 0.99924398],
       [0.06858773, 0.19386894],
       [0.45247623, 0.77078668],
       [0.84472911, 0.07078185],
       [0.47437914, 0.98580774],
       [0.61239199, 0.57302789]])

In [181]:
#Slicing operation
arr1[2][1]

0.7707866796854783

In [184]:
arr1[2:5][1]

array([0.84472911, 0.07078185])

In [185]:
arr=np.random.randint(1,100,(5,5))

In [186]:
arr

array([[94, 14, 32,  7, 24],
       [94, 54, 31, 30,  2],
       [81, 15, 41, 77, 24],
       [34, 11, 15, 80, 39],
       [17, 42,  3, 69, 84]])

In [188]:
# Extract all the data that is more than 50
arr>50 # Will give True and False

array([[ True, False, False, False, False],
       [ True,  True, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False,  True, False],
       [False, False, False,  True,  True]])

In [190]:
arr[arr>50] # In list form

array([94, 94, 54, 81, 77, 80, 69, 84])

In [193]:
arr[2:4,[1,2]]

array([[15, 41],
       [11, 15]])

In [196]:
arr[0][0]=500 # Reassigning the values

In [197]:
arr

array([[500,  14,  32,   7,  24],
       [ 94,  54,  31,  30,   2],
       [ 81,  15,  41,  77,  24],
       [ 34,  11,  15,  80,  39],
       [ 17,  42,   3,  69,  84]])

Functions in Array

In [199]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [200]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [2, 2, 1]])

In [201]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 1, 1]])

In [202]:
arr1+arr2 # will add the values present at the same location 

array([[4, 2, 4],
       [3, 3, 2],
       [4, 3, 2]])

In [203]:
arr1-arr2

array([[0, 0, 0],
       [1, 1, 0],
       [0, 1, 0]])

In [204]:
arr1+arr2

array([[4, 1, 4],
       [2, 2, 1],
       [4, 2, 1]])

In [205]:
arr1/arr2

array([[1., 1., 1.],
       [2., 2., 1.],
       [1., 2., 1.]])

In [206]:
# This can only be done for the same shape only 

In [208]:
arr1*arr2
# This is normal multiplication not matrix multiplication

array([[4, 1, 4],
       [2, 2, 1],
       [4, 2, 1]])

In [209]:
# Matrix Multiplication 
arr1@arr2

array([[9, 5, 7],
       [8, 5, 7],
       [8, 5, 7]])

In [211]:
arr1/0
# anything/0 in numpy will give infinite

/tmp/ipykernel_213/2533913817.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [213]:
arr1+100

array([[102, 101, 102],
       [102, 102, 101],
       [102, 102, 101]])

In [215]:
# Squaring each element
arr**2 

array([[250000,    196,   1024,     49,    576],
       [  8836,   2916,    961,    900,      4],
       [  6561,    225,   1681,   5929,    576],
       [  1156,    121,    225,   6400,   1521],
       [   289,   1764,      9,   4761,   7056]])

Broadcasting in Numpy

In [216]:
arr=np.zeros((4,4))

In [217]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [234]:
row=np.array([1,2,3,4])

In [235]:
row

array([1, 2, 3, 4])

In [236]:
arr+row # Now this linear array will be added in each of the row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [237]:
col=np.array(([1,2,3,4],[5,6,7,8]))

In [238]:
col

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [239]:
col.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [240]:
arr1=np.random.randint(1,4,(3,4))

In [241]:
arr1

array([[2, 1, 2, 1],
       [2, 3, 3, 2],
       [2, 1, 2, 1]])

In [243]:
np.sqrt(arr1) # To find square root 

array([[1.41421356, 1.        , 1.41421356, 1.        ],
       [1.41421356, 1.73205081, 1.73205081, 1.41421356],
       [1.41421356, 1.        , 1.41421356, 1.        ]])

In [244]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [ 7.3890561 , 20.08553692, 20.08553692,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183]])

In [245]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.30103   , 0.        ],
       [0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.        , 0.30103   , 0.        ]])